window.LESSON_VOCAB = [
  { ko: "기뻐", en: "happy (informal)", pl: "szczęśliwa / szczęśliwy" },
  { ko: "나 너무 기뻐", en: "I'm so happy.", pl: "Jestem taka szczęśliwa." },
  { ko: "나 세상에서 제일 기뻐", en: "I'm the happiest in the world.", pl: "Jestem najszczęśliwsza na świecie." },
  { ko: "너무", en: "too / so much", pl: "zbyt / tak bardzo" },
  { ko: "너", en: "you", pl: "ty" },
  { ko: "너 너무 완벽해", en: "You are so perfect.", pl: "Jesteś taka idealna / zbyt idealna." },
  { ko: "완벽해", en: "perfect (is)", pl: "idealna / idealny" },
  { ko: "완벽하잖아", en: "you're perfect, you know", pl: "jesteś idealna, wiesz" },
  { ko: "세상에서", en: "in the world", pl: "na świecie" },
  { ko: "제일", en: "the most / number one", pl: "najbardziej / naj-" },
  { ko: "너무 더워", en: "It's too hot.", pl: "Jest zbyt gorąco." },
  { ko: "너무 추워", en: "It's too cold.", pl: "Jest zbyt zimno." },
  { ko: "너무 핫해", en: "too hot (Konglish)", pl: "zbyt gorąco (anglicyzm)" },
  { ko: "더워", en: "hot (is)", pl: "gorąco" },
  { ko: "추워", en: "cold (is)", pl: "zimno" },
  { ko: "날씨", en: "weather", pl: "pogoda" },
  { ko: "날씨 거지 같네", en: "The weather is awful. (slang)", pl: "Pogoda jest okropna." },
  { ko: "거지", en: "beggar", pl: "żebrak" },
  { ko: "이웃", en: "neighbor", pl: "sąsiad" },
  { ko: "내", en: "my", pl: "mój / moja" },
  { ko: "내 이웃 그지 같네", en: "My neighbor is awful.", pl: "Mój sąsiad jest okropny." },
  { ko: "개", en: "dog", pl: "pies" },
  { ko: "개 같네", en: "awful / like a dog (slang)", pl: "okropne (slang)" },
  { ko: "같네", en: "is like… (casual ending)", pl: "jest jak… (potocznie)" },
  { ko: "나", en: "I", pl: "ja" }
];
