window.LESSON_VOCAB = [
  { ko: "포옹", en: "a hug (noun)", pl: "przytulenie" },
  { ko: "안다", en: "to hug (verb)", pl: "przytulać" },
  { ko: "안고 있어", en: "I'm hugging", pl: "przytulam cię (teraz)" },
  { ko: "안아줄게", en: "I'll hug you", pl: "przytulę cię" },
  { ko: "나는 널 꽉 안고 있어", en: "I'm hugging you tight", pl: "przytulam cię bardzo mocno" },
  { ko: "꽉", en: "tightly / firmly", pl: "mocno / bardzo mocno" },
  { ko: "널", en: "you (object, casual)", pl: "cię" },
  { ko: "나", en: "I", pl: "ja" },
  { ko: "나는", en: "I (topic)", pl: "ja" },
  { ko: "-고 있어", en: "am …ing (ongoing)", pl: "właśnie … (czynność trwa)" },
  { ko: "안아주다", en: "to hug someone (for them)", pl: "przytulać (kogoś)" },
  { ko: "보다", en: "to see / watch / look", pl: "widzieć / patrzeć" },
  { ko: "별로", en: "not really / not particularly", pl: "niezbyt / średnio" },
  { ko: "별로네", en: "not great / meh / nothing special", pl: "no cóż / średnio / nie za bardzo" },
  { ko: "다녀왔어", en: "I'm back (casual) — like ただいま", pl: "wróciłem / już jestem" },
  { ko: "다녀왔습니다", en: "I'm back (formal)", pl: "wróciłem (formalnie)" },
  { ko: "다녀왔어?", en: "Welcome back? (casual) — like おかえり", pl: "wróciłeś?" },
  { ko: "다녀오셨습니까", en: "Welcome back? (formal)", pl: "wrócił Pan/Pani?" },
  { ko: "다녀오다", en: "to go out and come back", pl: "wyjść i wrócić" }
];
