window.LESSON_VOCAB = [
  { pl: "cudowny / cudowna / cudowne", en: "wonderful", ko: "멋진 / 훌륭한" },
  { pl: "wspaniały / wspaniała", en: "amazing", ko: "대단한 (niesamowity)" },
  { pl: "idealny / idealna", en: "perfect", ko: "완벽한" },
  { pl: "najbardziej", en: "the most", ko: "가장 / 제일" },
  { pl: "na świecie", en: "in the world", ko: "세계에서" },
  { pl: "we wszechświecie", en: "in the universe", ko: "우주에서" },
  { pl: "na całym świecie", en: "in the whole world", ko: "전 세계에서" },
  { pl: "w całym wszechświecie", en: "in the whole universe", ko: "온 우주에서" },
  { pl: "cały / cała / całe / całym", en: "whole / entire", ko: "전체의 / 온" },
  { pl: "ja", en: "I", ko: "나" },
  { pl: "ty", en: "you (singular)", ko: "너 / 당신" },
  { pl: "on", en: "he", ko: "그" },
  { pl: "ona", en: "she", ko: "그녀" },
  { pl: "ono", en: "it (neuter)", ko: "그것" },
  { pl: "my", en: "we", ko: "우리" },
  { pl: "wy", en: "you (plural)", ko: "너희 / 여러분" },
  { pl: "oni / one", en: "they", ko: "그들" },
  { pl: "jestem", en: "I am", ko: "나는 ~이다" },
  { pl: "jesteś", en: "you are (sg.)", ko: "너는 ~이다" },
  { pl: "jest", en: "he/she/it is", ko: "그/그녀는 ~이다" },
  { pl: "jesteśmy", en: "we are", ko: "우리는 ~이다" },
  { pl: "jesteście", en: "you are (pl.)", ko: "너희는 ~이다" },
  { pl: "są", en: "they are", ko: "그들은 ~이다" },
  { pl: "Jesteś cudowny.", en: "You are wonderful. (to a man)", ko: "너는 멋져. (남성)" },
  { pl: "Jesteś cudowna.", en: "You are wonderful. (to a woman)", ko: "너는 멋져. (여성)" },
  { pl: "Jesteś wspaniały.", en: "You are amazing. (to a man)", ko: "너는 대단해. (남성)" },
  { pl: "Jesteś wspaniała.", en: "You are amazing. (to a woman)", ko: "너는 대단해. (여성)" },
  { pl: "Jesteś idealny.", en: "You are perfect. (to a man)", ko: "너는 완벽해. (남성)" },
  { pl: "Jesteś idealna.", en: "You are perfect. (to a woman)", ko: "너는 완벽해. (여성)" },
  { pl: "najlepszy / najlepsza", en: "the best", ko: "최고의" },
  { pl: "piękny / piękna", en: "beautiful", ko: "아름다운" },
  { pl: "Jesteś najbardziej wspaniała na świecie.", en: "You are the most amazing in the world", ko: "너는 세상에서 가장 대단해" },
  { pl: "Jesteś najbardziej cudowna.", en: "You are the most wonderful", ko: "너는 가장 멋져" }
];
