window.LESSON_VOCAB = [
  { pl: "Jestem szczęśliwy / szczęśliwa", en: "I am happy", ko: "행복해요 / 기뻐요" },
  { pl: "Cieszę się", en: "I'm glad / happy", ko: "기뻐요" },
  { pl: "Boję się", en: "I am afraid", ko: "무서워요" },
  { pl: "Uczę się", en: "I am learning", ko: "배우고 있어요" },
  { pl: "Myję się", en: "I wash myself", ko: "씻어요" },
  { pl: "Ubieram się", en: "I get dressed", ko: "옷 입어요" },
  { pl: "się", en: "myself / each other (reflexive)", ko: "재귀 조사 (~자신 / ~서로)" },
  { pl: "Jestem taka szczęśliwa", en: "I am so happy", ko: "너무 행복해요" },
  { pl: "Jestem tak bardzo szczęśliwa", en: "I am so very happy", ko: "정말 너무 행복해요" },
  { pl: "taka", en: "so / exactly (fem.)", ko: "그렇게 / 정말 (여성)" },
  { pl: "tak bardzo", en: "so much", ko: "그렇게 많이 / 너무" },
  { pl: "tak", en: "yes OR so / like that", ko: "네 / 그렇게" },
  { pl: "taki / taka / takie", en: "such / like this / so", ko: "그런 / 그렇게 (성별 변화)" },
  { pl: "właśnie tak", en: "like this / exactly", ko: "바로 그렇게" },
  { pl: "najszczęśliwsza", en: "the happiest (fem.)", ko: "가장 행복한 (여성)" },
  { pl: "Jestem najbardziej szczęśliwa na świecie", en: "I am the most happy in the world", ko: "세상에서 가장 행복해요" },
  { pl: "zbyt", en: "too", ko: "너무 (과도하게)" },
  { pl: "Jesteś zbyt idealna", en: "You are too perfect", ko: "너무 완벽해" },
  { pl: "idealny / idealna", en: "perfect / ideal", ko: "완벽한 / 이상적인" },
  { pl: "Jesteś zbyt gorący", en: "You are too hot", ko: "너무 섹시해 / 더워" },
  { pl: "Zbyt gorąco", en: "Too hot (weather)", ko: "너무 더워요" },
  { pl: "Za zimno", en: "Too cold", ko: "너무 추워요" },
  { pl: "Dziś pogoda jest okropna", en: "Today's weather is awful", ko: "오늘 날씨가 끔찍해요" },
  { pl: "szczęśliwy / szczęśliwa", en: "happy", ko: "행복한" }
];
