window.LESSON_VOCAB = [
  { pl: "przytulenie", en: "a hug (noun)", ko: "포옹" },
  { pl: "przytulasa", en: "a hug (casual, after chcę)", ko: "포옹 (구어)" },
  { pl: "Chcę przytulasa", en: "I want a hug", ko: "포옹하고 싶어" },
  { pl: "chcę", en: "I want", ko: "원해요 / ~고 싶어" },
  { pl: "Przytul mnie", en: "Hug me", ko: "안아줘" },
  { pl: "mnie", en: "me", ko: "나를" },
  { pl: "cię", en: "you (object)", ko: "너를" },
  { pl: "przytulać", en: "to hug", ko: "안아주다" },
  { pl: "Przytulam cię", en: "I'm hugging you", ko: "너를 안아주고 있어" },
  { pl: "tulić", en: "to cuddle / hug", ko: "껴안다 / 안아주다" },
  { pl: "Tulę cię", en: "I'm hugging / cuddling you", ko: "너를 안고 있어" },
  { pl: "Przytulę cię", en: "I'll hug you", ko: "안아줄게" },
  { pl: "przytulę", en: "I will hug", ko: "안아줄 거야" },
  { pl: "Przytulam cię bardzo mocno", en: "I'm hugging you very tight", ko: "너를 아주 꽉 안아주고 있어" },
  { pl: "bardzo mocno", en: "very tightly / very hard", ko: "아주 꽉 / 아주 세게" },
  { pl: "przytul", en: "hug! (imperative)", ko: "안아줘 (명령)" },
  { pl: "skarbie", en: "darling / sweetie", ko: "자기야 / 내 사랑" },
  { pl: "kotku", en: "kitty (nickname)", ko: "고양이야 (애칭)" },
  { pl: "misiu", en: "bear / teddy (nickname)", ko: "곰돌이 (애칭)" },
  { pl: "kocham cię", en: "I love you", ko: "사랑해" },
  { pl: "człowiek", en: "a person / human (singular)", ko: "사람 (한 명)" },
  { pl: "ludzie", en: "people (plural only)", ko: "사람들" },
  { pl: "niebo", en: "sky / heaven", ko: "하늘" },
  { pl: "ziemia", en: "earth / ground", ko: "땅" },
  { pl: "wszechświat", en: "universe", ko: "우주" },
  { pl: "księżyc", en: "moon", ko: "달" },
  { pl: "Księżyc jest dziś wyjątkowo piękny, czyż nie?", en: "The moon is exceptionally beautiful today, isn't it?", ko: "오늘 달이 유난히 아름답지 않아?" },
  { pl: "wyjątkowo", en: "exceptionally", ko: "유난히 / 특별히" },
  { pl: "czyż nie", en: "isn't it? / right? (tag)", ko: "~지 않아?" },
  { pl: "Księżyc jest dziś naprawdę piękny!", en: "The moon is really beautiful today!", ko: "오늘 달이 정말 아름다워!" },
  { pl: "naprawdę", en: "really / truly", ko: "정말" },
  { pl: "świat", en: "world", ko: "세상" },
  { pl: "świąt", en: "(of) holidays — NOT world!", ko: "명절 (세상 아님!)" },
  { pl: "Och, jak cudowną noc dziś mamy!", en: "Oh, what a wonderful night we have today!", ko: "오, 오늘 정말 멋진 밤이야!" },
  { pl: "cudowna noc", en: "wonderful night", ko: "멋진 / 환상적인 밤" },
  { pl: "dziś", en: "today", ko: "오늘" }
];
